# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec11256925b01a0867bded2e7e33c9aa6d4c62f38987f6c8447e72cf2beb1ccc9a8fc1c2347aa53206ed303f9be574cc1388f99ba3f4e3898bbebec677f60c14

test:
  secret_key_base: 9bd1d67b146b0ae3f9824301ed18c29acd8bd75d0a1d46fdd2bc52020c3756fe1ce10f53e60ed7b899f27fff7f8360c6ec8b4532ae671ac5d531b82a46518f27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  